version: '3'

services:
  tareasapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: tareas-docker
    container_name: tareasapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}

  db:
    image: mongo:5
    container_name: mongo-tareas
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-tareas
    volumes:
      - ./mongo:/data/db