// Generated by https://quicktype.io

export interface ITareas {
    tareas: Tarea[];
}

export interface Tarea {
    id_task:     string;
    name:        string;
    description: string;
    date:        string;
    date_end:    string;
    id_creator:  string;
}
